FROM python:3.11

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY .env .
COPY main.py .

EXPOSE 1411

CMD ["gunicorn", "--bind", "0.0.0.0:1411", "main:app"]